// Mock-data basert på Norwegian Fjord Explorer (Tromsø)
// https://www.norwegianfjordexplorer.com

export const mockTours = [
  {
    id: "nfe-001",
    slug: "arctic-king-crab-cruise",
    duration_hours: 4,
    price_from: 1290,
    price_to: null,
    max_capacity: 70,
    difficulty_level: "moderate",
    season_start: 1,
    season_end: 12,
    is_active: true,
    booking_url: "https://fjordexplorer.bilberry.app/web/products/75/calendar",
    image_url: "https://cdn.prod.website-files.com/66af610b3366d46c5654a663/67c195ef7a4e3c3400eec594_IMG-20250227-WA0042.avif",
  },
  {
    id: "nfe-002",
    slug: "classic-arctic-fjord-cruise",
    duration_hours: 4.5,
    price_from: 890,
    price_to: null,
    max_capacity: 70,
    difficulty_level: "easy",
    season_start: 1,
    season_end: 12,
    is_active: true,
    booking_url: "https://fjordexplorer.bilberry.app/web/products/52/calendar",
    image_url: "https://cdn.prod.website-files.com/66af610b3366d46c5654a663/692eff88372ec230f4ca7fc2_Kopi-av-_DSC2707-16_9-l.avif",
  },
  {
    id: "nfe-003",
    slug: "northern-lights-fjord-cruise",
    duration_hours: 3,
    price_from: 890,
    price_to: null,
    max_capacity: 70,
    difficulty_level: "easy",
    season_start: 9,
    season_end: 3,
    is_active: true,
    booking_url: "https://fjordexplorer.bilberry.app/web/products/54/calendar",
    image_url: "https://cdn.prod.website-files.com/66af610b3366d46c5654a663/67dd523b0b8ce16c28afe208_WhatsApp%20Image%202025-03-19%20at%2018.22.45_638d63ee.avif",
  },
  {
    id: "nfe-004",
    slug: "midday-arctic-explorer",
    duration_hours: 3,
    price_from: 590,
    price_to: null,
    max_capacity: 70,
    difficulty_level: "easy",
    season_start: 1,
    season_end: 12,
    is_active: true,
    booking_url: "https://www.norwegianfjordexplorer.com/tour-one",
    image_url: "https://cdn.prod.website-files.com/66af610b3366d46c5654a663/6915e968ac52a32d506a4539_3e09cb5d61ee73fbb1924e840b0993ff_i4As03YMZ1ApGlSTxUcMa.avif",
  },
  {
    id: "nfe-005",
    slug: "evening-polar-expedition",
    duration_hours: 3,
    price_from: 590,
    price_to: null,
    max_capacity: 70,
    difficulty_level: "easy",
    season_start: 9,
    season_end: 3,
    is_active: true,
    booking_url: "https://www.norwegianfjordexplorer.com/tour-two",
    image_url: "https://cdn.prod.website-files.com/66af610b3366d46c5654a663/68270bf104d0caa597cd617b_001957_Knut-Hansvold_www.nordnorge.com.avif",
  },
  {
    id: "nfe-006",
    slug: "jazz-cruise",
    duration_hours: 2.5,
    price_from: 498,
    price_to: null,
    max_capacity: 70,
    difficulty_level: "easy",
    season_start: 10,
    season_end: 3,
    is_active: true,
    booking_url: "https://www.norwegianfjordexplorer.com/tour-jazz-eng",
    image_url: "https://cdn.prod.website-files.com/66af610b3366d46c5654a663/67c194b807b181ce1f35c7ec_IMG-20250227-WA0038.avif",
  },
  {
    id: "nfe-007",
    slug: "captains-secret-bars",
    duration_hours: 4,
    price_from: 990,
    price_to: null,
    max_capacity: 20,
    difficulty_level: "easy",
    season_start: 1,
    season_end: 12,
    is_active: true,
    booking_url: "https://www.norwegianfjordexplorer.com/tour-captain-eng",
    image_url: "https://cdn.prod.website-files.com/66af610b3366d46c5654a663/687f3cbafc74761010c0a3b2_522217_10150657409571765_819774399_n%20(1)%20(1).jpg",
  },
];

export const mockTranslations: Record<string, Record<string, { name: string; description: string; highlights: string[]; included: string[]; meeting_point: string }>> = {
  "arctic-king-crab-cruise": {
    en: {
      name: "Arctic King Crab Cruise",
      description: "Hunt and catch real Arctic King Crabs aboard a comfortable explorer vessel in Tromsø, the Arctic capital. Enjoy a self-captured lunch freshly prepared onboard.",
      highlights: ["Catch your own king crab", "Fresh lunch from your catch", "Arctic wildlife spotting", "Stunning fjord scenery"],
      included: ["King crab catching experience", "Freshly prepared lunch", "Warm drinks", "Fishing equipment"],
      meeting_point: "Fridtjof Nansens plass, Tromsø",
    },
    de: {
      name: "Arktische Königskrabben-Kreuzfahrt",
      description: "Fangen Sie echte arktische Königskrabben an Bord eines komfortablen Expeditionsschiffs in Tromsø, der arktischen Hauptstadt. Genießen Sie ein selbst gefangenes Mittagessen, frisch an Bord zubereitet.",
      highlights: ["Eigene Königskrabbe fangen", "Frisches Mittagessen vom Fang", "Arktische Tierbeobachtung", "Atemberaubende Fjordlandschaft"],
      included: ["Königskrabben-Fangerlebnis", "Frisch zubereitetes Mittagessen", "Warme Getränke", "Angelausrüstung"],
      meeting_point: "Fridtjof Nansens plass, Tromsø",
    },
    fr: {
      name: "Croisière Crabe Royal Arctique",
      description: "Pêchez de vrais crabes royaux arctiques à bord d'un navire d'exploration confortable à Tromsø, la capitale arctique. Savourez un déjeuner fraîchement préparé à bord.",
      highlights: ["Pêchez votre propre crabe royal", "Déjeuner frais de votre pêche", "Observation de la faune arctique", "Paysages de fjord spectaculaires"],
      included: ["Expérience de pêche au crabe", "Déjeuner fraîchement préparé", "Boissons chaudes", "Équipement de pêche"],
      meeting_point: "Fridtjof Nansens plass, Tromsø",
    },
    es: {
      name: "Crucero de Cangrejo Real Ártico",
      description: "Pesque cangrejos reales árticos a bordo de un cómodo barco explorador en Tromsø, la capital ártica. Disfrute de un almuerzo recién preparado a bordo con su propia captura.",
      highlights: ["Pesque su propio cangrejo real", "Almuerzo fresco de su captura", "Avistamiento de fauna ártica", "Paisajes de fiordo impresionantes"],
      included: ["Experiencia de pesca de cangrejo", "Almuerzo recién preparado", "Bebidas calientes", "Equipo de pesca"],
      meeting_point: "Fridtjof Nansens plass, Tromsø",
    },
  },
  "classic-arctic-fjord-cruise": {
    en: {
      name: "Classic Arctic Fjord Cruise with Lunch",
      description: "A scenic daytime journey through the Arctic fjords featuring local polar exploration history, traditional narratives and a delicious lunch onboard MS Tromsø.",
      highlights: ["Polar exploration stories", "Arctic fjord scenery", "Traditional Norwegian lunch", "Historic MS Tromsø vessel"],
      included: ["Lunch onboard", "Polar storytelling", "Guided commentary"],
      meeting_point: "Fridtjof Nansens plass, Tromsø",
    },
    de: {
      name: "Klassische Arktische Fjordkreuzfahrt mit Mittagessen",
      description: "Eine malerische Tagesreise durch die arktischen Fjorde mit lokaler Polarforschungsgeschichte, traditionellen Erzählungen und einem köstlichen Mittagessen an Bord der MS Tromsø.",
      highlights: ["Polarforschungsgeschichten", "Arktische Fjordlandschaft", "Traditionelles norwegisches Mittagessen", "Historisches Schiff MS Tromsø"],
      included: ["Mittagessen an Bord", "Polare Geschichten", "Geführter Kommentar"],
      meeting_point: "Fridtjof Nansens plass, Tromsø",
    },
    fr: {
      name: "Croisière Classique Fjord Arctique avec Déjeuner",
      description: "Un voyage panoramique de jour à travers les fjords arctiques avec l'histoire de l'exploration polaire locale, des récits traditionnels et un délicieux déjeuner à bord du MS Tromsø.",
      highlights: ["Histoires d'exploration polaire", "Paysages de fjord arctique", "Déjeuner norvégien traditionnel", "Navire historique MS Tromsø"],
      included: ["Déjeuner à bord", "Récits polaires", "Commentaire guidé"],
      meeting_point: "Fridtjof Nansens plass, Tromsø",
    },
    es: {
      name: "Crucero Clásico Fiordo Ártico con Almuerzo",
      description: "Un viaje panorámico diurno por los fiordos árticos con historia de exploración polar local, relatos tradicionales y un delicioso almuerzo a bordo del MS Tromsø.",
      highlights: ["Historias de exploración polar", "Paisajes de fiordo ártico", "Almuerzo noruego tradicional", "Barco histórico MS Tromsø"],
      included: ["Almuerzo a bordo", "Relatos polares", "Comentario guiado"],
      meeting_point: "Fridtjof Nansens plass, Tromsø",
    },
  },
  "northern-lights-fjord-cruise": {
    en: {
      name: "Classic Northern Lights Fjord Cruise",
      description: "An unforgettable evening cruise through the Arctic fjords in search of the Northern Lights. Enjoy a hot meal and polar history tales while scanning the sky for the aurora borealis.",
      highlights: ["Northern Lights hunting", "Hot evening meal", "Polar history stories", "Arctic night atmosphere"],
      included: ["Dinner onboard", "Polar history commentary", "Northern Lights viewing", "Warm drinks"],
      meeting_point: "Fridtjof Nansens plass, Tromsø",
    },
    de: {
      name: "Klassische Nordlichter-Fjordkreuzfahrt",
      description: "Eine unvergessliche Abendkreuzfahrt durch die arktischen Fjorde auf der Suche nach den Nordlichtern. Genießen Sie eine warme Mahlzeit und polare Geschichten.",
      highlights: ["Nordlichterjagd", "Warmes Abendessen", "Polare Geschichten", "Arktische Nachtatmosphäre"],
      included: ["Abendessen an Bord", "Polargeschichten", "Nordlichter-Beobachtung", "Warme Getränke"],
      meeting_point: "Fridtjof Nansens plass, Tromsø",
    },
    fr: {
      name: "Croisière Classique Aurores Boréales",
      description: "Une croisière inoubliable en soirée à travers les fjords arctiques à la recherche des aurores boréales. Savourez un repas chaud et des récits polaires.",
      highlights: ["Chasse aux aurores boréales", "Repas chaud du soir", "Récits d'histoire polaire", "Atmosphère nocturne arctique"],
      included: ["Dîner à bord", "Commentaire sur l'histoire polaire", "Observation des aurores", "Boissons chaudes"],
      meeting_point: "Fridtjof Nansens plass, Tromsø",
    },
    es: {
      name: "Crucero Clásico Aurora Boreal en Fiordo",
      description: "Un crucero nocturno inolvidable por los fiordos árticos en busca de la aurora boreal. Disfrute de una cena caliente y relatos de historia polar.",
      highlights: ["Caza de auroras boreales", "Cena caliente", "Historias polares", "Atmósfera nocturna ártica"],
      included: ["Cena a bordo", "Comentario de historia polar", "Observación de auroras", "Bebidas calientes"],
      meeting_point: "Fridtjof Nansens plass, Tromsø",
    },
  },
  "midday-arctic-explorer": {
    en: {
      name: "Tromsø Mid-Day Arctic Explorer Cruise",
      description: "A flexible daytime polar expedition cruise with open bar, historical narratives and stunning views of the Arctic landscape. Choose morning or afternoon departure.",
      highlights: ["Open bar included", "Flexible departure times", "Polar expedition history", "Arctic panoramic views"],
      included: ["Open bar", "Polar historical commentary", "Onboard service"],
      meeting_point: "Fridtjof Nansens plass, Tromsø",
    },
    de: {
      name: "Tromsø Mittags-Arktis-Entdeckerkreuzfahrt",
      description: "Eine flexible Tages-Polarexpeditionskreuzfahrt mit offener Bar, historischen Erzählungen und atemberaubender Aussicht auf die arktische Landschaft.",
      highlights: ["Offene Bar inklusive", "Flexible Abfahrtszeiten", "Polarexpeditionsgeschichte", "Arktisches Panorama"],
      included: ["Offene Bar", "Polarhistorischer Kommentar", "Bordservice"],
      meeting_point: "Fridtjof Nansens plass, Tromsø",
    },
    fr: {
      name: "Croisière Explorateur Arctique de Midi à Tromsø",
      description: "Une croisière d'expédition polaire flexible en journée avec bar ouvert, récits historiques et vues panoramiques sur le paysage arctique.",
      highlights: ["Bar ouvert inclus", "Horaires de départ flexibles", "Histoire d'expédition polaire", "Vues panoramiques arctiques"],
      included: ["Bar ouvert", "Commentaire historique polaire", "Service à bord"],
      meeting_point: "Fridtjof Nansens plass, Tromsø",
    },
    es: {
      name: "Crucero Explorador Ártico de Mediodía en Tromsø",
      description: "Un crucero de expedición polar flexible durante el día con barra libre, relatos históricos y vistas impresionantes del paisaje ártico.",
      highlights: ["Barra libre incluida", "Horarios flexibles", "Historia de expedición polar", "Vistas panorámicas árticas"],
      included: ["Barra libre", "Comentario histórico polar", "Servicio a bordo"],
      meeting_point: "Fridtjof Nansens plass, Tromsø",
    },
  },
  "evening-polar-expedition": {
    en: {
      name: "Tromsø Evening Polar Expedition Cruise",
      description: "A magical evening voyage to the outer reaches of Tromsø, docking at a secret destination. Experience the Northern Lights from a famous onboard bar with Arctic atmosphere.",
      highlights: ["Secret destination dock", "Northern Lights viewing", "Famous onboard bar", "Arctic evening atmosphere"],
      included: ["Onboard bar access", "Northern Lights viewing opportunity"],
      meeting_point: "Fridtjof Nansens plass, Tromsø",
    },
    de: {
      name: "Tromsø Abend-Polarexpeditionskreuzfahrt",
      description: "Eine magische Abendfahrt zu den äußeren Bereichen von Tromsø mit Anlegen an einem geheimen Ziel. Erleben Sie die Nordlichter von einer berühmten Bordbar.",
      highlights: ["Geheimer Anlegeplatz", "Nordlichter-Beobachtung", "Berühmte Bordbar", "Arktische Abendatmosphäre"],
      included: ["Zugang zur Bordbar", "Nordlichter-Beobachtungsmöglichkeit"],
      meeting_point: "Fridtjof Nansens plass, Tromsø",
    },
    fr: {
      name: "Croisière Expédition Polaire de Soirée à Tromsø",
      description: "Un voyage magique en soirée vers les confins de Tromsø, accostant à une destination secrète. Observez les aurores boréales depuis le célèbre bar à bord.",
      highlights: ["Accostage destination secrète", "Observation des aurores", "Célèbre bar à bord", "Atmosphère arctique en soirée"],
      included: ["Accès au bar à bord", "Possibilité d'observer les aurores"],
      meeting_point: "Fridtjof Nansens plass, Tromsø",
    },
    es: {
      name: "Crucero Expedición Polar Nocturna en Tromsø",
      description: "Un viaje nocturno mágico a las afueras de Tromsø, atracando en un destino secreto. Observe las auroras boreales desde el famoso bar a bordo.",
      highlights: ["Atraque en destino secreto", "Observación de auroras", "Famoso bar a bordo", "Atmósfera ártica nocturna"],
      included: ["Acceso al bar a bordo", "Oportunidad de ver auroras"],
      meeting_point: "Fridtjof Nansens plass, Tromsø",
    },
  },
  "jazz-cruise": {
    en: {
      name: "Jazz Cruise – Jazz i Mørketia",
      description: "Live jazz in the dark season! Enjoy local Tromsø jazz artists performing onboard MS Tromsø while cruising around Tromsøya island. Includes traditional Bacalao or whale stew.",
      highlights: ["Live jazz performance", "Local Tromsø artists", "Cruise around Tromsøya", "Traditional Arctic cuisine"],
      included: ["Live jazz concert", "Bacalao or whale stew", "Cruise around Tromsøya island"],
      meeting_point: "MS Tromsø, Tromsø harbour",
    },
    de: {
      name: "Jazz-Kreuzfahrt – Jazz i Mørketia",
      description: "Live-Jazz in der dunklen Jahreszeit! Genießen Sie lokale Tromsøer Jazzkünstler an Bord der MS Tromsø während einer Fahrt um die Insel Tromsøya. Inklusive traditionellem Bacalao oder Walgulasch.",
      highlights: ["Live-Jazz-Aufführung", "Lokale Tromsøer Künstler", "Fahrt um Tromsøya", "Traditionelle arktische Küche"],
      included: ["Live-Jazz-Konzert", "Bacalao oder Walgulasch", "Kreuzfahrt um Tromsøya"],
      meeting_point: "MS Tromsø, Tromsø Hafen",
    },
    fr: {
      name: "Croisière Jazz – Jazz i Mørketia",
      description: "Du jazz live pendant la saison sombre ! Profitez d'artistes jazz locaux de Tromsø à bord du MS Tromsø en naviguant autour de l'île de Tromsøya. Inclus : Bacalao ou ragoût de baleine.",
      highlights: ["Concert de jazz live", "Artistes locaux de Tromsø", "Tour de Tromsøya", "Cuisine arctique traditionnelle"],
      included: ["Concert de jazz live", "Bacalao ou ragoût de baleine", "Croisière autour de Tromsøya"],
      meeting_point: "MS Tromsø, port de Tromsø",
    },
    es: {
      name: "Crucero Jazz – Jazz i Mørketia",
      description: "¡Jazz en vivo en la temporada oscura! Disfrute de artistas de jazz locales de Tromsø a bordo del MS Tromsø mientras navega alrededor de la isla Tromsøya. Incluye Bacalao o guiso de ballena.",
      highlights: ["Concierto de jazz en vivo", "Artistas locales de Tromsø", "Navegación alrededor de Tromsøya", "Cocina ártica tradicional"],
      included: ["Concierto de jazz en vivo", "Bacalao o guiso de ballena", "Crucero alrededor de Tromsøya"],
      meeting_point: "MS Tromsø, puerto de Tromsø",
    },
  },
  "captains-secret-bars": {
    en: {
      name: "Captain's Secret Bars & Hidden Corners",
      description: "A private guided tour starting onboard MS Tromsø with the captain's welcome drink, followed by dinner at a local bistro and a walking tour through Tromsø's secret bars and hidden corners.",
      highlights: ["Captain's welcome drink onboard", "Dinner at local bistro", "Secret bars of Tromsø", "Walking tour through hidden corners"],
      included: ["Captain's drink onboard", "Dinner (meatballs or salmon rolls)", "Guided walking tour", "Drinks at Skarven seaman bar"],
      meeting_point: "Fridtjof Nansens plass 4, MS Tromsø",
    },
    de: {
      name: "Geheime Bars & Versteckte Ecken des Kapitäns",
      description: "Eine private geführte Tour, die an Bord der MS Tromsø mit dem Willkommensdrink des Kapitäns beginnt, gefolgt von einem Abendessen im lokalen Bistro und einem Rundgang durch Tromsøs geheime Bars.",
      highlights: ["Willkommensdrink des Kapitäns", "Abendessen im lokalen Bistro", "Geheime Bars von Tromsø", "Rundgang durch versteckte Ecken"],
      included: ["Kapitänsdrink an Bord", "Abendessen (Fleischbällchen oder Lachsröllchen)", "Geführter Rundgang", "Getränke in der Skarven-Seemannsbar"],
      meeting_point: "Fridtjof Nansens plass 4, MS Tromsø",
    },
    fr: {
      name: "Bars Secrets & Coins Cachés du Capitaine",
      description: "Une visite privée guidée commençant à bord du MS Tromsø avec le verre de bienvenue du capitaine, suivie d'un dîner dans un bistro local et d'une visite à pied des bars secrets de Tromsø.",
      highlights: ["Verre de bienvenue du capitaine", "Dîner au bistro local", "Bars secrets de Tromsø", "Visite à pied des coins cachés"],
      included: ["Verre du capitaine à bord", "Dîner (boulettes ou rouleaux de saumon)", "Visite guidée à pied", "Boissons au bar Skarven"],
      meeting_point: "Fridtjof Nansens plass 4, MS Tromsø",
    },
    es: {
      name: "Bares Secretos y Rincones Ocultos del Capitán",
      description: "Un tour privado guiado que comienza a bordo del MS Tromsø con la bebida de bienvenida del capitán, seguido de cena en un bistro local y un recorrido a pie por los bares secretos de Tromsø.",
      highlights: ["Bebida de bienvenida del capitán", "Cena en bistro local", "Bares secretos de Tromsø", "Recorrido por rincones ocultos"],
      included: ["Bebida del capitán a bordo", "Cena (albóndigas o rollos de salmón)", "Tour guiado a pie", "Bebidas en el bar Skarven"],
      meeting_point: "Fridtjof Nansens plass 4, MS Tromsø",
    },
  },
};

export const mockCategories = [
  { id: "cat-001", slug: "fjord", translations: { en: "Fjord Cruise", de: "Fjordkreuzfahrt", fr: "Croisière Fjord", es: "Crucero Fiordo" } },
  { id: "cat-002", slug: "northern-lights", translations: { en: "Northern Lights", de: "Nordlichter", fr: "Aurores Boréales", es: "Aurora Boreal" } },
  { id: "cat-003", slug: "food", translations: { en: "Food & Dining", de: "Essen & Trinken", fr: "Gastronomie", es: "Gastronomía" } },
  { id: "cat-004", slug: "culture", translations: { en: "Culture", de: "Kultur", fr: "Culture", es: "Cultura" } },
  { id: "cat-005", slug: "nightlife", translations: { en: "Nightlife", de: "Nachtleben", fr: "Vie Nocturne", es: "Vida Nocturna" } },
  { id: "cat-006", slug: "wildlife", translations: { en: "Wildlife", de: "Wildtiere", fr: "Faune", es: "Fauna" } },
];

export const mockTourCategories: Record<string, string[]> = {
  "arctic-king-crab-cruise": ["fjord", "food", "wildlife"],
  "classic-arctic-fjord-cruise": ["fjord", "food", "culture"],
  "northern-lights-fjord-cruise": ["fjord", "northern-lights", "food"],
  "midday-arctic-explorer": ["fjord", "culture"],
  "evening-polar-expedition": ["fjord", "northern-lights", "nightlife"],
  "jazz-cruise": ["fjord", "culture", "food", "nightlife"],
  "captains-secret-bars": ["nightlife", "food", "culture"],
};
